<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ValidatorsRuleMessage\**" />
    <EmbeddedResource Remove="ValidatorsRuleMessage\**" />
    <None Remove="ValidatorsRuleMessage\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ValidatorsRulesResourceMessages\ValidatorsRulesResourceMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ValidatorsRulesResourceMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="ValidatorsRulesResourceMessages\ValidatorsRulesResourceMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ValidatorsRulesResourceMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
