@ControleDeAcesso26.API_HostAddress = https://localhost:7186

GET {{ControleDeAcesso26.API_HostAddress}}/usuario/RecuperarUsuarios

###

POST {{ControleDeAcesso26.API_HostAddress}}/usuario/CriarUsuario
Content-Type: application/json

{
  //RequestCriarUsuarioJson
}

###
