//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeAcesso26.Exceptions.ValidatorsRulesResourceMessages {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidatorsRulesResourceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatorsRulesResourceMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleDeAcesso26.Exceptions.ValidatorsRulesResourceMessages.ValidatorsRulesReso" +
                            "urceMessages", typeof(ValidatorsRulesResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro desconhecido.
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O apelido já existe.
        /// </summary>
        public static string USUARIO_APELIDO_JA_EXISTE {
            get {
                return ResourceManager.GetString("USUARIO_APELIDO_JA_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O apelido do usuário não pode estar vazio.
        /// </summary>
        public static string USUARIO_APELIDO_VAZIO {
            get {
                return ResourceManager.GetString("USUARIO_APELIDO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sem alterações. Para atualizar, você deve preencher ao menos um nome ou apelido.
        /// </summary>
        public static string USUARIO_FALHA_ATUALIZAR {
            get {
                return ResourceManager.GetString("USUARIO_FALHA_ATUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sem alterações. Para atualizar, você deve preencher ao menos um nome ou apelido diferente.
        /// </summary>
        public static string USUARIO_FALHA_ATUALIZAR_2 {
            get {
                return ResourceManager.GetString("USUARIO_FALHA_ATUALIZAR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sem alterações. Para atualizar, você deve preencher ao menos um apelido diferente.
        /// </summary>
        public static string USUARIO_FALHA_ATUALIZAR_3 {
            get {
                return ResourceManager.GetString("USUARIO_FALHA_ATUALIZAR_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sem alterações. Para atualizar, você deve preencher ao menos um nome diferente.
        /// </summary>
        public static string USUARIO_FALHA_ATUALIZAR_4 {
            get {
                return ResourceManager.GetString("USUARIO_FALHA_ATUALIZAR_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado.
        /// </summary>
        public static string USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do usuário não pode estar vazio.
        /// </summary>
        public static string USUARIO_NOME_VAZIO {
            get {
                return ResourceManager.GetString("USUARIO_NOME_VAZIO", resourceCulture);
            }
        }
    }
}
